language: python
python:
  - "nightly"
  - "3.8"
  - "3.7"
  - "3.6"
  - "3.5"
  - "pypy3"
  # - "3.9"
  # 3.9 doesn't exist yet.
install:
  - pip install -r requirements.txt || curl https://bootstrap.pypa.io/get-pip.py | python3 && pip install -r requirements.txt
  - pip3 install pytest
  - pip3 install -r requirements.txt

cache: pip
jobs:
  include:
    - name: "MacOS Xcode9.4 test"
      os: osx
      osx_image: xcode9.4
      lanaguge: generic
    - name: "MacOS Xcode10 test"
      os: osx
      osx_image: xcode10
      lanaguge: generic
    - name: "MacOS Xcode11 test"
      os: osx
      osx_image: xcode11
      lanaguge: generic
    - name: "MacOS Xcode12 test"
      os: osx
      osx_image: xcode12
      lanaguge: generic
    - name: "MacOS Xcode12 test"
      os: osx
      osx_image: xcode12
      lanaguge: generic
    - name: "Unbuntu 12"
      os: linux
      dist: precise
    - name: "Ubuntu 14"
      os: linux
      dist: trusty
    - name: "Ubuntu 16"
      os: linux
      dist: xenial
    - name: "Ubuntu 18"
      os: linux
      dist: bionic

  fast_finish: true
  allow_failures:
    - python: "nightly"
script:
  - pytest tests/ -vvv
notifications:
  email:
    recipients:
      - bryan.hu.cn@gmail.com
    on_success: change # default: change
    on_failure: always # default: always
git:
  quiet: true
