language: python
os:
  - linux
dist: xenial
python:
  - "nightly"
  - "3.8"
  - "3.7"
  - "3.6"
  - "3.5"
  - "pypy3"
  # - "3.9"
  # 3.9 doesn't exist yet.
install:
  # - pip install pytest-asyncio
  - pip install -r requirements.txt
cache: pip
jobs:
  include:
    - python: "nightly"
    - python: "3.8"
    - python: "3.7"
    - python: "3.6"
    - python: "3.5"
    - python: "pypy3"
    - name: "MacOs tests"
      os: osx
      before_install: pip install pytest
      lanaguge: generic
  fast_finish: true
  allow_failures:
    - python: "nightly"
script:
  - pytest tests/ -vvv
notifications:
  email:
    recipients:
      - bryan.hu.cn@gmail.com
    on_success: change # default: change
    on_failure: always # default: always
git:
  quiet: true
