language: python
os: linux
dist: xenial
python:
  - "nightly"
  - "3.8"
  - "3.7"
  - "3.6"
  - "3.5"
  - "pypy3"
  # - "3.9"
  # 3.9 doesn't exist yet.
install:
  - pip install -r requirements.txt
  - pip3 install pytest
  - pip3 install -r requirements.txt

cache: pip
jobs:
  include:
    - python: "nightly"
    - python: "3.8"
    - python: "3.7"
    - python: "3.6"
    - python: "3.5"
    - python: "pypy3"
    - os: osx
      osx_image: xcode12
      lanaguge: generic
    - os: osx
      osx_image: xcode11
      lanaguge: generic
    - os: osx
      osx_image: xcode10
      lanaguge: generic
    - os: osx
      osx_image: xcode9.4
      lanaguge: generic
  fast_finish: true
  allow_failures:
    - python: "nightly"
script:
  - pytest tests/ -vvv
notifications:
  email:
    recipients:
      - bryan.hu.cn@gmail.com
    on_success: change # default: change
    on_failure: always # default: always
git:
  quiet: true
