---
# appveyor.yml
version: "1.0.{build}"
environment:
  matrix:
    - TOXENV: py27
    - TOXENV: py35
    - TOXENV: py36
    - TOXENV: py37

build: off

install:
  - pip install pytest

test_script:
  - pytest
