---
# appveyor.yml
version: "1.2.0.{build}"
# environment:
#   matrix:
#     - TOXENV: py27
#     - TOXENV: py35
#     - TOXENV: py36
#     - TOXENV: py37

build: on

before_build:
  - pip3 install --upgrade pip3

build_script:
  - make python3.8 || make python3

install:
  - pip install pytest

test_script:
  - pytest
