# This is a basic workflow to help you get started with Actions

name: Black

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
   - name: Black Check
     uses: jpetrucciani/black-check@19.10b0
 

